application: wassr-fav
version: 1
runtime: python
api_version: 1

handlers:
  - url: /favicon.ico
    static_files: static/images/favicon.ico
    upload: static/images/favicon.ico
    mime_type: image/vnd.microsoft.icon

  - url: /static
    static_dir: static

  - url: /admin/.*
    script: $PYTHON_LIB/google/appengine/ext/admin/
    login: admin

  - url: .*
    script: wassr-fav.py

